### ISSUE TITLE
problems with latest git port (git-heads.v2.44.0.20240318_110959.zos)

### ISSUE THREAD

**Issue by mgrossmann** [ZOSOpenTools/gitport#117]
Hello,

today I updated git from `git-2.43.0.20240229_200332.zos` to `git-heads.v2.44.0.20240318_110959.zos`.

After reverting a source code change via `git checkout mysource` the source file was damaged due to
incorrect new lines. Switching back to the old version of git solved this issue.

(my source file are tagged as IBM-1141)

Regards, Mike

**Comment by IgorTodorovskiIBM** [comment]
This seems to be due to the inclusion of the z/OS Open Tools iconv library. Previously we were using the z/OS native iconv implementation.

**Comment by mfsysprog** [comment]
Can confirm we had the same issue when testing latest release

**Comment by IgorTodorovskiIBM** [comment]
Also reproducible via iconv command line:

```
 iconv -f IBM-037 -t IBM-1047 my_037.txt > output
```
The file `output` will have an incorrect newline added.

The dev release of zopen iconv fixes it though. However, the library calls (`iconv_open`) need to be updated since that is what git uses.

For now I'll revert back to the native iconv

**Comment by IgorTodorovskiIBM** [comment]
Ok to close this?

**Comment by mgrossmann** [comment]
Yes
