### ISSUE TITLE
git doesnt like https repos

### ISSUE THREAD

**Issue by IgorTodorovskiIBM** [ZOSOpenTools/gitport#14]
git clone https://github.com/TheMozg/awk-raycaster
Cloning into 'awk-raycaster'...
warning: templates not found /jenkins/workspace/Port-Build/install/share/git-core/templates
fatal: Unable to find remote helper for 'https'

**Comment by IgorTodorovskiIBM** [comment]
to enable https support, we need to build git with curl.

**Comment by MikeFultonDev** [comment]
@IgorTodorovskiIBM @HarithaIBM Building with the latest 'dev' code on Nov 10, I see this:
```
git clone 'https://git.savannah.gnu.org/git/gnulib.git' 'gnulib'
Unknown CURL message received: 16777216
```

This prevents us from building m4 from 'git' (m4 itself as part of the build uses git to pull down gnulib)

**Comment by MikeFultonDev** [comment]
appears to work with the latest git drop
