### ISSUE TITLE
git submodule init doesn't seem to work

### ISSUE THREAD

**Issue by MikeFultonDev** [ZOSOpenTools/gitport#16]
Running m4 'git' build, I get:

```
Cloning into 'gnulib'...
Updating files: 100% (10666/10666), done.
trap: func_require_gnulib_submodule 38: func_require_gnulib_tool 5: func_gnulib_tool 4: func_reconfigure 40: func_bootstrap 19: ./bootstrap 5420: FSUM7327 signal number 13 not conventional
bootstrap: running: git submodule init -- gnulib
fatal: 'submodule' appears to be a git command, but we were not
able to execute it. Maybe git-submodule is broken?
bootstrap: running: git submodule update -- gnulib
fatal: 'submodule' appears to be a git command, but we were not
able to execute it. Maybe git-submodule is broken?
```

**Comment by MikeFultonDev** [comment]
This is simple to reproduce. Create a repo, then cd into it and issue:

```
FULTONM : /SYSTEM/tmp/zotsampleport : > git submodule add https://github.com/chaconinc/DbConnector
fatal: 'submodule' appears to be a git command, but we were not
able to execute it. Maybe git-submodule is broken?
```

Note this doesn't work with the Rocket git either.

**Comment by MikeFultonDev** [comment]
next step: build git with --submodules in config?

https://stackoverflow.com/questions/13805658/how-do-i-enable-submodule-cloning-in-git-buildpackage

**Comment by MikeFultonDev** [comment]
There is no --submodules option to build with - the git-submodule is there and it 'works' but only if:
- you add `$HOME/zopen/prod/git/libexec/git-core` to your PATH
- you run git-submodule directly and not git submodule

So this has something to do with missing env vars or invalid PATH settings I think

**Comment by IgorTodorovskiIBM** [comment]
It works if we set the shebang line of git-submodule to `#!/bin/env bash` 

We may want to modify this line: https://github.com/ZOSOpenTools/gitport/blob/rebase/tarballpatches/config.mak.uname.patch#L13

**Comment by mfsysprog** [comment]
I think that is a good solution. The rocket port of git introduced a GIT_SHELL environment variable to solve this it seems, so I think that the rocket version will work if you set GIT_SHELL to the location of bash (or to /bin/env bash probably :-))
I've created a litte test script that shows if the hashbang actually works:
#!/bin/env bash
ps -p $$

If you run this from the regular shell you will see that you actually are running under bash, with #!bash it will just run under /bin/sh.

**Comment by MikeFultonDev** [comment]
@mfsysprog would you be willing to open a PR up with the fix?

**Comment by MikeFultonDev** [comment]
@IgorTodorovskiIBM @mfsysprog should we also change PYTHON_PATH and PERL_PATH as well?

**Comment by MikeFultonDev** [comment]
So my early results:
- if you skip testing, then what gets installed seems to work pretty well
- if you run tests, they fail with: `/bin/env bash: FSUM7351 not found` (and similar for perl). So the fix isn't quite that straight-forward.

This does give me a work-around to make progress with m4 'git' build, so I'll move on to that if someone else would like to tackle this one...

**Comment by mfsysprog** [comment]
/bin/env bash basically will find the bash executable in the currently set path if I'm correct. Can you explain in what way you run the tests? I'm guessing that in the perl test scripts for example the shebang is !#/bin/sh, so if the regular path environment variable (from /etc/profile and .profile I think) don't have the directory with bash in their path it will fail.

**Comment by IgorTodorovskiIBM** [comment]
I forgot to add that the PR https://github.com/ZOSOpenTools/gitport/pull/18 resolved this issue. We added bash as a dependency in https://github.com/ZOSOpenTools/gitport/blob/main/buildenv because the tests actually make use of bash syntax.  Running `make test` will run the tests.

**Comment by MikeFultonDev** [comment]
closing... @IgorTodorovskiIBM re-open if this is not fixed but i think it is.
