### ISSUE TITLE
Option or environment variable to Ignore file tags

### ISSUE THREAD

**Issue by IgorTodorovskiIBM** [ZOSOpenTools/gitport#26]
I would like to have an option (preferably an environment variable) to totally ignoring file tags and make git works exactly like it is on non-filetag platforms.

_Originally posted by @ccw-1 in https://github.com/ZOSOpenTools/gitport/issues/21#issuecomment-1353513945_

**Comment by MikeFultonDev** [comment]
done now right @IgorTodorovskiIBM ? If so, can we close?

**Comment by IgorTodorovskiIBM** [comment]
Yes, documented here: https://zosopentools.github.io/meta/#/Guides/GitOnZOS?id=file-tag-verifications but I should also document it in the README
