### ISSUE TITLE
'git' build requires more tools to bootstrap (with a 'git' build, not a 'tarball' build)

### ISSUE THREAD

**Issue by MikeFultonDev** [ZOSOpenTools/gitport#3]
Output from bootstrap:

bootstrap:   error: Prerequisite 'help2man' not found. Please install it, or
bootstrap:          'export HELP2MAN=/path/to/help2man'.
bootstrap:   error: Prerequisite 'makeinfo' not found. Please install it, or
bootstrap:          'export MAKEINFO=/path/to/makeinfo'.
bootstrap:   error: Prerequisite 'xz' not found. Please install it, or
bootstrap:          'export XZ=/path/to/xz'.
bootstrap:   error: HACKING explains how to obtain these prerequisite programs:
bootstrap:          Program    Min_version Homepage
bootstrap:          -----------------------------------------------------------
bootstrap:          help2man   1.29        http://www.gnu.org/s/help2man
bootstrap:          make       3.81        http://www.gnu.org/s/make
bootstrap:          makeinfo   4.8         http://www.gnu.org/s/texinfo
bootstrap:          xz	       4.999.8beta http://tukaani.org/xz
bootstrap:          autoconf   2.64        http://www.gnu.org/s/autoconf
bootstrap:          automake   1.11.1      http://www.gnu.org/s/automake
bootstrap:          -----------------------------------------------------------

**Comment by ZOSOpenTools** [comment]
note this is only required for a 'git' build not a 'tarball' build

**Comment by IgorTodorovskiIBM** [comment]
We have a functioning git build now, so we can close this off.
