### ISSUE TITLE
when git is first 'set up' on a z/OS system, it should set up the GIT_SSL_CAINFO

### ISSUE THREAD

**Issue by MikeFultonDev** [ZOSOpenTools/gitport#32]
There are a few questions.
- Do we want to use this opportunity to update the cacert via `zopen update-cacert`?
- Do we want to have `meta` setup copy it's starter cacert.pem up into the `boot` directory so various tools can use it?

We also need to do this for openssl and curl.

I would like to not keep the cacert in the meta package like we do today because customers that only want our open source tools don't need anything in meta except this cacert file (although they would need it if they wanted to refresh their cacert and didn't want to manually download it with curl.

My opinion:
- No, we don't need to do the `zopen update-cacert` - it should be sufficient to just tell them of the function and also how to manually download in an info message
- Yes, we should have `meta` copy it's starter cacert.pem up to boot and we should probably 'hide' it since we don't want people using it (maybe make it .cacert.pem ?). We should update all the tools to not specify a cert but instead use the configured cert that git and curl will have

@IgorTodorovskiIBM would appreciate your thoughts here before I start coding...

**Comment by lbdyck** [comment]
The option should be part of the git installation since it seems specific to that (I could be wrong).

How is this different from the ~/.ssh/id_rsa files?

**Comment by MikeFultonDev** [comment]
fixed now.
