### ISSUE TITLE
git cannot process untagged files if they are opened with fopen

### ISSUE THREAD

**Issue by IgorTodorovskiIBM** [ZOSOpenTools/gitport#35]
When files such as `.git/config` are untagged, git cannot process them. This is because for some reason, fopen automatically changes the ccsid of such files to 1047.  This can be overridden by the environment variables _BPXK_CCSIDS, but it can also affect other tooling.

I think a better solution is to override fopen similar to how we override open so that they both handle autoconversion using the same logic.

**Comment by IgorTodorovskiIBM** [comment]
Handling this in zoslib via commit https://github.com/ibmruntimes/zoslib/commit/d9c1b6d2ca9444284e3731ba80cc7e3ac37cefeb

**Comment by MikeFultonDev** [comment]
@IgorTodorovskiIBM is this fixed now?

**Comment by MikeFultonDev** [comment]
@IgorTodorovskiIBM closing this off - re-open if not fixed
