### ISSUE TITLE
git readme missing info

### ISSUE THREAD

**Issue by lbdyck** [ZOSOpenTools/gitport#37]
Some info missing from the readme.md is:

1. What pre-req/co-req tools are required for git
2. how to download and install if only git and req's are desired
3. simple how to install and configure for production use

**Comment by lbdyck** [comment]
Don't forget to add info on the certificate (pem) file.

**Comment by MikeFultonDev** [comment]
@lbdyck and @IgorTodorovskiIBM is this done now?

**Comment by MikeFultonDev** [comment]
closing this off - @lbdyck please re-open if this isn't addressed.
