### ISSUE TITLE
git production installation and use

### ISSUE THREAD

**Issue by lbdyck** [ZOSOpenTools/gitport#38]
It would be nice to have a simple process to:

1. download git and requisite tools
2. install into a common location
3. document/assist in updating the /etc/profile and whatever else

Same for updating an existing installation.

**Comment by MikeFultonDev** [comment]
see: https://github.com/orgs/ZOSOpenTools/discussions/110 for a discussion about tackling this issue for all tools, not just git.

**Comment by IgorTodorovskiIBM** [comment]
@lbdyck with zopen now available, can we close this off?

**Comment by lbdyck** [comment]
closing with thanks
