### ISSUE TITLE
.env issues Warning: you need to set GIT_SSL_CAINFO to a pem file if you want to use git with SSH when pem file path has already been specified in .gitconfig

### ISSUE THREAD

**Issue by ccw-1** [ZOSOpenTools/gitport#39]
.env issues Warning: you need to set GIT_SSL_CAINFO to a pem file if you want to use git with SSH when pem file path has already been specified in .gitconfig

```
[http]
    sslVerify = true
    sslCAInfo = /<somewhere>/cacert.pem
```

**Comment by IgorTodorovskiIBM** [comment]
@MikeFultonDev maybe we can check the $HOME/.gitconfig as well before issuing this message? https://github.com/ZOSOpenTools/gitport/blob/main/buildenv#L101

**Comment by lbdyck** [comment]
When was this made a requirement with git?  I don't have it using the Rocket port and I don't recall seeing it with git for windows.

Can it be bypassed/ignored?

**Comment by IgorTodorovskiIBM** [comment]
We provide our own CA certificates. Right now it's just a warning, but that's a good point about GIT_SSL_NO_VERIFY. The same could be said about sslVerify = false.

**Comment by lbdyck** [comment]
So you're saying that the gitport will provide the certificate or by 'we' do you mean the site?

**Comment by MikeFultonDev** [comment]
@IgorTodorovskiIBM is this fixed? can it be closed?

**Comment by IgorTodorovskiIBM** [comment]
Yes, I will close it off
