### ISSUE TITLE
hash error

### ISSUE THREAD

**Issue by ccw-1** [ZOSOpenTools/gitport#42]
Description of issue:
If the environment variable GIT_COMMITTER_DATE is set AND GIT_COMMITTER_NAME and/or GIT_COMMITTER_EMAIL is set, the Git committer name and/or email will be replaced with the contents of GIT_COMMITTER_DATE respectively.
Steps to reproduce:
Setup empty repository
mkdir testdir1 && cd testdir1
git init
touch hello
chtag -c819 hello
git add hello
2. Set committer info
export GIT_COMMITTER_NAME='Jane Doe'
export GIT_COMMITTER_EMAIL='Jane.Doe@example.com'
export GIT_COMMITTER_DATE=2019-04-03T13:30:35-04:00
3. Commit and show output
git commit -m 'test commit'
git --no-replace-objects cat-file commit HEAD
# ACTUAL OUTPUT
tree f966952d7e0715683ee935d201cd4ab22736c831
author Jane Doe <Jane.Doe@example.com> 1675113490 -0500
committer Jane Doe <Jane.Doe@example.com> 1675113490 -0500

test commit

# EXPECTED OUTPUT
tree f966952d7e0715683ee935d201cd4ab22736c831
author Jane Doe <Jane.Doe@example.com> 1675113490 -0500
committer 2019-04-03T13:30:35-04:00 <2019-04-03T13:30:35-04:00> 1554312635 -0400

test commit

**Comment by IgorTodorovskiIBM** [comment]
This is fixed in the latest release https://github.com/ZOSOpenTools/gitport/releases/tag/gitport_445
