### ISSUE TITLE
Incorrect file tagging ?

### ISSUE THREAD

**Issue by lbdyck** [ZOSOpenTools/gitport#44]
On your git (2.39) the file is thus:
t ISO8859-1  T=on -rw-rw-rw-  1 LBDYCK  ZOWEDEV   55982 Jan 31 15:03 zginstall.rex
but on git 2.26.2 it is:
t IBM-1047   T=on -rw-rw-rw-  1 SPLBD   SYS1      55982 Jan 31 12:05 zginstall.rex
This is the REXX code that ‘extracts’ the file from the git repository
cmd = 'cd' localrep'/'zigirep ,
   '&& git show' hcommit':'element ,
   '| cat >' file
If I change it thus:
cmd = 'cd' localrep'/'zigirep ,
   '&& git show' hcommit':'element ,
   '| cat >' file ‘&& chtag -tc IBM-1047’ file
Which does work.
I then get this when I try to edit the file:
The z/OS UNIX file contains a record with a length greater than 32750. Records of this size are not supported by the ISPF editor.
It would seem that ‘git show’ is working differently from the older rocket git.
Bug, Feature, or by design.

**Comment by IgorTodorovskiIBM** [comment]
I see that you are piping the git show output to cat. Is this `/bin/cat` or the `cat` from coreutils in zopen? That cat will always tag and convert output to ascii.

**Comment by lbdyck** [comment]
I changed the code to this and still have the same issue:

`cmd = 'cd' localrep'/'zigirep ,        
   '&& git show' hcommit':'element ,   
   '>' file                            `

**Comment by lbdyck** [comment]
Realized cat was not required.  But it does work with git 2.26 just fine.

**Comment by lbdyck** [comment]
This is what I have on  my work system for this use case using Rocket git version 2.26.2-78        

t IBM-1047    T=on  -rw-rw-rw-   1 SPLBD    SYS1        1875 Feb  1 05:03 CHGSTR       

But with Rocket git version 2.26.2-84 and with yours I get:

t ISO8859-1   T=on  -rw-rw-rw-   1 LBDYCK   ZOWEDEV     1875 Feb  1 08:06 CHGSTR        

So something must have changed with the base git - it *should* honor the files encoding which I would hope git retained somewhere.

But this isn't unique to you it  appears - but may be a general git 'bug'

**Comment by IgorTodorovskiIBM** [comment]
It may be the _TAG_REDIR_OUT envar, which we set in the .env files:

Try unsetting it at the end of your .profile:
```
[\u@\h \w]$ git show efcd72401c0869ae6e105a5c3d9c1bca1be746a6 > newfile.txt && ls -lT newfile.txt
t ISO8859-1   T=on  -rw-rw-r--   1 ITODORO  CDEV     17695395 Feb  1 08:45 newfile.txt
[\u@\h \w]$ unset _TAG_REDIR_OUT
[\u@\h \w]$ rm newfile.txt && git show efcd72401c0869ae6e105a5c3d9c1bca1be746a6 > newfile.txt && ls -lT newfile.txt
t IBM-1047    T=on  -rw-rw-r--   1 ITODORO  CDEV     17695395 Feb  1 08:46 newfile.txt
```

Let me know if that helps

**Comment by lbdyck** [comment]
On both systems this is the variable: _TAG_REDIR_OUT=txt

Doing the unset resolved the problem - wow - that's esoteric....

Thank you

**Comment by lbdyck** [comment]
I've updated my code thus and it now works:

cmd = 'cd' localrep'/'zigirep ,       
   '&& unset _TAG_REDIR_OUT' ,        
   '&& git show' hcommit':'element ,  
   '>' file                           
dhrc = docmd(cmd)

**Comment by IgorTodorovskiIBM** [comment]
I agree, it's not very clear. It's documented here: https://www.ibm.com/docs/en/zos/2.2.0?topic=descriptions-sh-invoke-shell#sh__envarb



_TAG_REDIR_OUT=TXT | Redirected stdout will be tagged as:TXTFLAG = ON, CCSID = program CCSID at the time of the first write (if not already tagged)
-- | --


The program ccsid for z/OS Open Tools is ascii. You may want to do the same for _TAG_REDIR_ERR

**Comment by IgorTodorovskiIBM** [comment]
I'll make a note in the readme about this

**Comment by lbdyck** [comment]
Thanks - for zigi purposes I'm not concerned with the _ERR :)

wow - strange - great job finding the solution.

**Comment by IgorTodorovskiIBM** [comment]
Thanks for opening these issues! Oh and my apologies for ending the call abruptly yesterday! 

Once you confirm everything is working smoothly, I think it would be great if we can incorporate zigi into the zopen framework. That way someone can run:
```
zopen download zigi
```
And after downloading, they can source the .env or run setup.sh and it will set it up for their environment. 

Here's an example for a library we manage:
https://github.com/ZOSOpenTools/zoslibport

**Comment by lbdyck** [comment]
The tagging issue has been resolved with an update to the 317dev branch of zigi.  that will be incorporated into the master branch in the near future.

Once the zopen-setup issues are resolved, or some other simple packaging that incorporates git with its pre/co-reqs, then packaging zigi with your may be doable.  Can you perhaps reference repositories outside of zosopentools?  Perhaps github.com/zigi/zigi ???

**Comment by MikeFultonDev** [comment]
One thing we could do @lbdyck would be to create a 'zigiport' which would be very small and would then let you host zigi wherever you want but let the z/OS Open Tools community be able to provide it. We have done this with zoslib which is hosted elsewhere but it lets us use it.

**Comment by lbdyck** [comment]
Fyi – your git/etc is now working *g*r*e*a*t* and I’ve adjusted my git show to extract a historical level so that it does this:

 



 

And now I have the correct encoding.

 

There is still a ‘challenge’ with the ispf hilite that I have to look into but it works and invoking ispf edit does not cause any errors.

 

 

Lionel B. Dyck <><

Website:  <https://www.lbdsoftware.com> https://www.lbdsoftware.com

Github:  <https://github.com/lbdyck> https://github.com/lbdyck

 

“Worry more about your character than your reputation. Character is what you are, reputation merely what others think you are.”   - - - John Wooden

**Comment by IgorTodorovskiIBM** [comment]
That's great to hear! I've set up zigiport - https://github.com/ZOSOpenTools/zigiport/tree/main, which will allow us to install zigi via zopen. If you're good with the buildenv file, then we can try to kick off a build. I've also given you write access.

I'm currently working on implementing runtime dependency support for zopen, so once that is in, we can add the dependencies to the buildenv config and when you run `zopen install zigi` it will auto download the dependencies.

**Comment by lbdyck** [comment]
I'm going to decline for now until I know more. I'd like to see a simple package to install git with pre/co-reqs first.  Then lets discuss how to best do a zigi install without having to maintain multiple repositories with the zigi code.

**Comment by IgorTodorovskiIBM** [comment]
Sure! We can definitely wait until the runtime dep feature is implemented in zopen.

Also, I just wanted to clarify that the zigiport repo in ZOSOpenTools would only have the instructions on how to pull and package zigi. It would still pull the code from https://github.com/zigi/zigi.  See here: https://github.com/ZOSOpenTools/zigiport/blob/main/buildenv#L1 .

If you want to discuss in more detail in a call, we'd be happy to set it up.

**Comment by lbdyck** [comment]
No call as yet but things are looking VERY promising.

**Comment by MikeFultonDev** [comment]
Is it safe to close this issue now @lbdyck ?

**Comment by IgorTodorovskiIBM** [comment]
@lbdyck can we close this off?

**Comment by lbdyck** [comment]
closing with thanks
