### ISSUE TITLE
man directory and files missing

### ISSUE THREAD

**Issue by lbdyck** [ZOSOpenTools/gitport#50]
see subject

**Comment by IgorTodorovskiIBM** [comment]
Failed to build for me because asciidoc is not installed. After looking at the docs, we need to port asciidoc and xmlto for the documentation:
```
 - To build and install documentation suite, you need to have
   the asciidoc/xmlto toolchain.  Because not many people are
   inclined to install the tools, the default build target
   ("make all") does _not_ build them.
```

**Comment by IgorTodorovskiIBM** [comment]
asciidoc: https://github.com/asciidoc-py/asciidoc-py
xmlto: https://releases.pagure.org/xmlto/xmlto-0.0.28.tar.gz
xslt: https://download.gnome.org/sources/libxslt/1.1/libxslt-1.1.37.tar.xz

**Comment by MikeFultonDev** [comment]
Here is the info in the install - we might be able to do less work if we do 'make quick-install-man'

```
 - To build and install documentation suite, you need to have
   the asciidoc/xmlto toolchain.  Because not many people are
   inclined to install the tools, the default build target
   ("make all") does _not_ build them.

   "make doc" builds documentation in man and html formats; there are
   also "make man", "make html" and "make info". Note that "make html"
   requires asciidoc, but not xmlto. "make man" (and thus make doc)
   requires both.

   "make install-doc" installs documentation in man format only; there
   are also "make install-man", "make install-html" and "make
   install-info".

   Building and installing the info file additionally requires
   makeinfo and docbook2X.  Version 0.8.3 is known to work.

   Building and installing the pdf file additionally requires
   dblatex.  Version >= 0.2.7 is known to work.

   All formats require at least asciidoc 8.4.1. Alternatively, you can
   use Asciidoctor (requires Ruby) by passing USE_ASCIIDOCTOR=YesPlease
   to make. You need at least Asciidoctor version 1.5.

   There are also "make quick-install-doc", "make quick-install-man"
   and "make quick-install-html" which install preformatted man pages
   and html documentation. To use these build targets, you need to
   clone two separate git-htmldocs and git-manpages repositories next
   to the clone of git itself.

   The minimum supported version of docbook-xsl is 1.74.
```

**Comment by MikeFultonDev** [comment]
I was able to:
- download the latest tarball for git-manpages  into a directory in 'gitport' with: `curl -L https://mirrors.edge.kernel.org/pub/software/scm/git/git-manpages-2.9.5.tar.xz -o git-manpages-2.9.5.tar.xz` (I am not sure if this set of manpages corresponds with the git tarball - it's the latest there is)
- untar the tarball and then 'git init' it with a 'master' branch and add the man files 
- do `zopen build -s` and then manually do: `make quick-install-man`. This installs the man pages into 'prod' correctly.
- do a `man git`
![image](https://user-images.githubusercontent.com/61100689/224574500-15f3f9e7-a4cd-4820-bf2a-776fdbf944a7.png)

**Comment by IgorTodorovskiIBM** [comment]
Nice find, that is definitely a simpler solution!

**Comment by IgorTodorovskiIBM** [comment]
The man pages are now available, @lbdyck, can we close this off?

**Comment by lbdyck** [comment]
closing with thanks
