### ISSUE TITLE
validate configuration

### ISSUE THREAD

**Issue by MikeFultonDev** [ZOSOpenTools/gitport#52]
Go through patch: https://github.com/ZOSOpenTools/gitport/blob/0f0ae0c02de6ced6a062f9ab36a1bda75f415fa7/tarballpatches/config.mak.uname.patch#L19 and make sure these are appropriate and consistent (or a good reason not to be) with the Rocket port

**Comment by IgorTodorovskiIBM** [comment]
We should probably include libpcre2 now that it's ported

**Comment by MikeFultonDev** [comment]
@IgorTodorovskiIBM has libpcre2 been included? If not, can you open an issue? If yes, can you close this off?

**Comment by IgorTodorovskiIBM** [comment]
Yes, it is now included, we can close this off
