### ISSUE TITLE
upgrade failure

### ISSUE THREAD

**Issue by lbdyck** [ZOSOpenTools/gitport#64]
![image](https://user-images.githubusercontent.com/42328411/229485711-90e53c7a-1123-455a-8ff7-a22d2e42df41.png)

**Comment by lbdyck** [comment]
Changed to the boot directory and it worked 
![image](https://user-images.githubusercontent.com/42328411/229485957-275e56e4-b288-438f-9c55-2d6d513d2f07.png)

**Comment by IgorTodorovskiIBM** [comment]
@lbdyck this should be working now, can we close this off?

**Comment by lbdyck** [comment]
closing with thanks
