### ISSUE TITLE
git log issue (2.40 and 2.41)  

### ISSUE THREAD

**Issue by lbdyck** [ZOSOpenTools/gitport#72]
using command `git log --cc -m -n 3`

Notice the `diff` is missing :( 

with 2.26

![image](https://github.com/ZOSOpenTools/gitport/assets/42328411/5c449dc1-f565-4eed-9524-997767112a98)

With 2.41.0 (and with 2.40.1)

![image](https://github.com/ZOSOpenTools/gitport/assets/42328411/816cb3c9-f1fc-4d21-aa46-8d0d078ca8ce)

**Comment by IgorTodorovskiIBM** [comment]
What does the `-m` option do? If I remove it, I get a diff output. I see the same result when running git on Linux.

**Comment by lbdyck** [comment]
this is what it does - but I found it wasn't needed for git 2.26 so i removed it from zigi

![image](https://github.com/ZOSOpenTools/gitport/assets/42328411/06e37afa-360b-4262-ae97-97ebfa032ea6)
****
