### ISSUE TITLE
git blame doesn't work on ebcdic files

### ISSUE THREAD

**Issue by covener** [ZOSOpenTools/gitport#76]
Hi, please see test repo here with 1 file each: https://github.ibm.com/ecovener/git-example

I am using 2.41.0 on PLPSC, but rocket git fails the same way:

```
 $ git blame postinst.c |head -c 255
00000000 (Not Committed Yet 2023-07-07 13:23:19 -0400 1) ñâ(ä?>ÃÑÀÁ>ÈÑ/%|ä|ë?ÍÊÄÁ(/ÈÁÊÑ/%¢+ää|&ßêñåçCOVENER@PLPSC:~/SRC/git-test (main) $
$ git blame README |head -c 255
^76b2371 (Eric Covener 2023-07-07 13:20:40 -0400 1) I am
^76b2371 (Eric Covener 2023-07-07 13:20:40 -0400 2)   Ascii

```

In case it matters, not a zopen bash:
GNU bash, version 4.2.53(2)-release (i370-ibm-openedition)

**Comment by lbdyck** [comment]
Not good - just tried it via ZIGI and I get the same error.

**Comment by lbdyck** [comment]
my testing was with the zot bash

**Comment by lbdyck** [comment]
THANK YOU

**Comment by lbdyck** [comment]
This issue needs to be reopened as I am still hitting it

**Comment by lbdyck** [comment]
Repo                 Your version         Latest Tag           Dependencies                   Status     Quality                    
gitport              Not installed        Releaseline_gitport_1137 bash less ncurses perl         Blue       88 tests pass out of 91
 tests - 96.70% success rate

**Comment by IgorTodorovskiIBM** [comment]
@covener can you confirm if you're still hitting it as well?

**Comment by covener** [comment]
@IgorTodorovskiIBM it works for me now, going from 2.39.1 older zopen to 2.41.0 updated today:

```
$  which git; git -v ;git blame postinst.c |head -2
/u/WASTST1/zopen/prod/git/bin/git
git version 2.41.0
^76b2371 (Eric Covener 2023-07-07 13:20:40 -0400    1) /*-----------------------------------------------------------------
^76b2371 (Eric Covener 2023-07-07 13:20:40 -0400    2) --
```

**Comment by lbdyck** [comment]
Just upgraded the gitport and still get this: 
![image](https://github.com/ZOSOpenTools/gitport/assets/42328411/4567d6e3-1e66-4ef0-b4c6-255ca05bdeb0)

trying the above from Covener: 
![image](https://github.com/ZOSOpenTools/gitport/assets/42328411/cc2abe9f-9f96-4f7e-933c-3c5d253edc71)

**Comment by lbdyck** [comment]
Arg!  it works - the zopen upgrade went to zopen/prod and my env is set for zopen/boot

hoping for an improved zopen soon :)

Feel free to close this issue
