### ISSUE TITLE
Gitport "Can't locate strict.pm"

### ISSUE THREAD

**Issue by LittleSilver33** [ZOSOpenTools/gitport#91]
Although PERL is installed on the z/OS system (running zopen list confirms this), I am still unable to build Gitport because it is unable to locate the strict.pm in @INC. I worked with another IBM person to attempt to reconfigure PERL again before rebuilding and that did not work either. The IBM person that I talked to mentioned that it may have something to do with CPAN, but I am unsure.

**Comment by IgorTodorovskiIBM** [comment]
Hi, are you able to update perl again. You can run zopen upgrade perl or `zopen build -u -v`. The -u will update all of the buildenv dependencies. Let me know if that helps or if the issue still persists.

**Comment by EdenBendheim** [comment]
The issue still persists for me.

**Comment by IgorTodorovskiIBM** [comment]
Hmm, zopen build does cache the config state so if you are rebuiding from the same directory, then it may be using the old perl.

Can you try wiping your git-* directory and log directory and rebuilding?

```
cd gitport
rm -rf log git-*
zopen build -u -v
```

**Comment by EdenBendheim** [comment]
Alright, I'll give it a shot :)

**Comment by IgorTodorovskiIBM** [comment]
@EdenBendheim is this resolved? Can we close?

**Comment by EdenBendheim** [comment]
> @EdenBendheim is this resolved? Can we close?

Zach continued with testing this, @LittleSilver33 was any progress made?
