### ISSUE TITLE
Remove - and validate - setting environment variables in shell for git

### ISSUE THREAD

**Issue by MikeFultonDev** [ZOSOpenTools/gitport#92]
In [buildenv](https://github.com/ZOSOpenTools/gitport/blob/41ce3d4295f3c2919afd30842c8f0895e1c98dd3/buildenv#L100) we should only need to set the environment variables on in the binary (e.g. keep zopen_append_to_zoslib_env and remove zopen_append_to_env)

**Comment by IgorTodorovskiIBM** [comment]
This is done, will close
